---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - certs.core.rakshitgondwal.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - certs.core.rakshitgondwal.io
  resources:
  - certificates/finalizers
  verbs:
  - update
- apiGroups:
  - certs.core.rakshitgondwal.io
  resources:
  - certificates/status
  verbs:
  - get
  - patch
  - update
