apiVersion: v1
kind: Service
metadata:
  name: nginx-tls-service
  namespace: default
spec:
  selector:
    app: nginx-tls
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30001
  type: NodePort
