apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-tls
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-tls
  template:
    metadata:
      labels:
        app: nginx-tls
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 443
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/nginx/certs
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: tls-certs
          secret:
            secretName: my-certificate-secret
        - name: nginx-config
          configMap:
            name: nginx-config
